export const AMENITY_KEYS = [
  "wifi",
  "parking",
  "pool",
  "jacuzzi",
  "barbecue",
  "beach_access",
  "mountain_view",
  "garden",
  "terrace",
  "dishwasher",
  "washing_machine",
  "dryer",
  "tv",
  "air_conditioning",
  "heating",
  "gym",
  "elevator",
  "baby_bed",
  "pets_allowed",
  "smoking_allowed",
] as const

export type AmenityKey = (typeof AMENITY_KEYS)[number]

export const AMENITY_LABELS: Record<AmenityKey, string> = {
  wifi: "Wi-Fi",
  parking: "Parking",
  pool: "Piscine",
  jacuzzi: "Jacuzzi",
  barbecue: "Barbecue",
  beach_access: "Accès plage",
  mountain_view: "Vue montagne",
  garden: "Jardin",
  terrace: "Terrasse",
  dishwasher: "Lave-vaisselle",
  washing_machine: "Lave-linge",
  dryer: "Sèche-linge",
  tv: "Télévision",
  air_conditioning: "Climatisation",
  heating: "Chauffage",
  gym: "Salle de sport",
  elevator: "Ascenseur",
  baby_bed: "Lit bébé",
  pets_allowed: "Animaux acceptés",
  smoking_allowed: "Fumeurs acceptés",
}
